version: "3.9"

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./api/vol:/vol/static
      - ./nginx/htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - client
      - api
      - channels
      - celery-flower

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /client/node_modules
      - ./client:/usr/src/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    env_file:
      - ./config/envFiles/django/develop/.env
    volumes:
      - ./api:/usr/src/app
    command: ./docker-entrypoint-dev.sh
    depends_on:
      - db
      - smtp4dev
      - redis

  celery:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    env_file:
      - ./config/envFiles/django/develop/.env
    volumes:
      - ./api:/usr/src/app
    command: celery -A config worker -l info
    depends_on:
      - db
      - smtp4dev
      - redis

  celery-beat:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    env_file:
      - ./config/envFiles/django/develop/.env
    volumes:
      - ./api:/usr/src/app
    command: celery -A config beat -l info
    depends_on:
      - db
      - smtp4dev
      - redis

  celery-flower:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    env_file:
      - ./config/envFiles/django/develop/.env
    volumes:
      - ./api:/usr/src/app
    command: celery -A config flower --url_prefix=/flower --basic_auth=user:password
    depends_on:
      - db
      - smtp4dev
      - redis

  channels:
    build:
      dockerfile: Dockerfile
      context: ./api
    env_file:
      - ./config/envFiles/django/develop/.env
    volumes:
      - ./api:/usr/src/app
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
    depends_on:
      - db
      - smtp4dev
      - redis

  api-test:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    env_file:
      - ./config/envFiles/django/develop/.env
    volumes:
      - ./api:/usr/src/app
    command: ptw
    depends_on:
      - db
      - smtp4dev
      - redis

  db:
    image: postgres:13-alpine
    env_file:
      - ./config/envFiles/postgres/develop/.env
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_backups:/db_backups

  smtp4dev:
    image: rnwood/smtp4dev:3.1.3-ci20211206101
    restart: always
    ports:
      - "1025:80"
      - "2525:25"
      - "143:143"
    volumes:
      - smtp4dev-data:/smtp4dev

  redis:
    image: redis:7.0.4-alpine3.16
    restart: always
    volumes:
      - ./redis/redis-sample.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  pgdata:
  static-data:
  smtp4dev-data:
